---
- name: Setup EC2 instance
  hosts: all
  become: true
  become_user: root


  tasks:
  - name: Setting server timezone
    community.general.timezone:
      name: Africa/Lagos
    changed_when: true
    tags: play

  - name: Setting server hostname
    ansible.builtin.hostname:
      name: server.amzn2.local
    changed_when: true
    tags: play

  - name: Checking for updates and upgrades
    ansible.builtin.yum:
      update_cache: true
    changed_when: true
    tags: play

  - name: Installing Amazon Linux Extras
    ansible.builtin.yum:
      name:
        - amazon-linux-extras
        - yum-utils
    changed_when: true
    tags: play

  - name: Enabling PHP 8.1 Topic
    ansible.builtin.command:
      cmd: amazon-linux-extras enable php8.1
    changed_when: true
    tags: play

  - name: Completing yum transactions
    ansible.builtin.command:
      cmd: yum-complete-transaction
    changed_when: true
    tags: play

  - name: Checking for updates and upgrades
    ansible.builtin.yum:
      update_cache: true
    changed_when: true
    tags: play

  - name: Installing PHP 8.1
    ansible.builtin.command:
      cmd: amazon-linux-extras install php8.1
    changed_when: true
    tags: play

  - name: Installing PHP 8.1 modules
    ansible.builtin.yum:
      name:
        - php8.1-common
        - php8.1-mysql
        - php8.1-xml
        - php8.1-xmlrpc
        - php8.1-curl
        - php8.1-gd
        - php8.1-imagick
        - php8.1-cli
        - php8.1-dev
        - php8.1-imap
        - php8.1-mbstring
        - php8.1-opcache
        - php8.1-soap
        - php8.1-zip
        - php8.1-redis
        - php8.1-intl
      state: present
    changed_when: true
    tags: play

  - name: Checking for updates and upgrades
    ansible.builtin.yum:
      update_cache: true
    changed_when: true
    tags: play

  - name: Installing Nginx
    ansible.builtin.yum:
      name:
        - nginx
    changed_when: true
    tags: play

  - name: Starting Nginx and enabling at boot
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: true
    changed_when: true
    tags: play

  - name: Creating www directory
    ansible.builtin.file:
      path: /var/www
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: true
    changed_when: true
    tags: play

  - name: Creating domain directory
    ansible.builtin.file:
      path: /var/www/hostname_local
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: true
    changed_when: true
    tags: play

  - name: Copying php file
    ansible.builtin.copy:
      src: ~/stateless_app/index.php
      dest: /var/www/hostname_local
      owner: www-data
      group: www-data
      mode: '0644'
      recurse: true
    changed_when: true
    tags: play

  - name: Creating assets directory
    ansible.builtin.file:
      path: /var/www/hostname_local/assets
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
    changed_when: true
    tags: play

  - name: Copying css style
    ansible.builtin.copy:
      src: ~/stateless_app/assets/main.css
      dest: /var/www/hostname_local/assets
      owner: www-data
      group: www-data
      mode: '0644'
    changed_when: true
    tags: play

  - name: Copying favicon
    ansible.builtin.copy:
      src: ~/stateless_app/assets/favicon.ico
      dest: /var/www/hostname_local/assets
      owner: www-data
      group: www-data
      mode: '0644'
    changed_when: true
    tags: play

  - name: Creating domain server block in Nginx
    ansible.builtin.file:
      path: /etc/nginx/sites-available/hostname_local
      state: touch
      mode: '0644'
    changed_when: true
    tags: play

  - name: Add domain server block content
    ansible.builtin.blockinfile:
      path: /etc/nginx/sites-available/hostname_local
      block: |
        server {
          listen  80;
          server_name hostname.local www.hostname.local;

          location / {
            root  /usr/share/nginx/html;
            index index.php  index.html index.htm;

            error_page  500 502 503 504  /50x.html;
            location = /50x.html {
              root  /usr/share/nginx/html;
              }
      marker: ""
    changed_when: true
    tags: play

  - name: Create domain symlink in nginx
    ansible.builtin.command:
      cmd: sudo ln -s /etc/nginx/sites-available/hostname_local /etc/nginx/sites-enabled/
    changed_when: true
    tags: play
