apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: skylarng89/webthree:v1.0
        ports:
        - containerPort: 80
