apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    app: nginx
  namespace: webapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer