---
- name: Setup EC2 instance
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Setting server timezone
      community.general.timezone:
        name: Africa/Lagos
      changed_when: true
      tags: play

    - name: Set server hostname
      ansible.builtin.hostname:
        name: ip-10-0-2-133.eu-west-2.compute.internal
      changed_when: true
      tags: play

    - name: Checking for updates and upgrades
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      changed_when: true
      tags: play

    - name: Adding system dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
      changed_when: true
      tags: play

    - name: Adding PHP PPA Repo
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present
      changed_when: true
      tags: play

    - name: Checking for updates and upgrades
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      changed_when: true
      tags: play

    - name: Installing PHP 7.4
      ansible.builtin.apt:
        name:
          - php7.4-fpm
      changed_when: true
      tags: play

    - name: Installing PHP 7.4
      ansible.builtin.apt:
        name:
          - php7.4-common
          - php7.4-mysql
          - php7.4-xml
          - php7.4-xmlrpc
          - php7.4-curl
          - php7.4-gd
          - php7.4-imagick
          - php7.4-cli
          - php7.4-dev
          - php7.4-imap
          - php7.4-mbstring
          - php7.4-opcache
          - php7.4-soap
          - php7.4-zip
          - php7.4-redis
          - php7.4-intl
        state: present
      changed_when: true
      tags: play

    - name: Installing Nginx
      ansible.builtin.apt:
        name:
          - nginx
      changed_when: true
      tags: play

    - name: Creating www directory
      ansible.builtin.file:
        path: /var/www
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        recurse: true
      changed_when: true
      tags: play

    - name: Copying php file
      ansible.builtin.copy:
        src: ~/stateless_app/index.php
        dest: /var/www
        owner: ubuntu
        group: ubuntu
        mode: "0644"
      changed_when: true
      tags: play

    - name: Creating assets directory
      ansible.builtin.file:
        path: /var/www/assets
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"
      changed_when: true
      tags: play

    - name: Copying css style
      ansible.builtin.copy:
        src: ~/stateless_app/assets/main.css
        dest: /var/www/assets
        owner: ubuntu
        group: ubuntu
        mode: "0644"
      changed_when: true
      tags: play

    - name: Copying favicon
      ansible.builtin.copy:
        src: ~/stateless_app/assets/favicon.ico
        dest: /var/www/assets
        owner: ubuntu
        group: ubuntu
        mode: "0644"
      changed_when: true
      tags: play

    - name: Changing domain folder ownership
      ansible.builtin.file:
        path: /var/www
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: true
      changed_when: true
      tags: play

    - name: Changing index.php file ownership
      ansible.builtin.file:
        path: /var/www/index.php
        owner: www-data
        group: www-data
        mode: "0644"
      changed_when: true
      tags: play

    - name: Changing main.css file ownership
      ansible.builtin.file:
        path: /var/www/assets/main.css
        owner: www-data
        group: www-data
        mode: "0644"
      changed_when: true
      tags: play

    - name: Changing main.css file ownership
      ansible.builtin.file:
        path: /var/www/assets/favicon.ico
        owner: www-data
        group: www-data
        mode: "0644"
      changed_when: true
      tags: play
