---
- name: Setup EC2 instance
  hosts: all
  become: true

  tasks:
    - name: Setting server timezone
      community.general.timezone:
        name: Africa/Lagos
      changed_when: true
      tags: play

    - name: Checking for updates and upgrades
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      changed_when: true
      tags: play

    - name: Installing Apache
      ansible.builtin.apt:
        name:
          - apache2
      changed_when: true
      tags: play

    - name: Removing default index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
      changed_when: true
      tags: html

    - name: Creating index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: touch
      changed_when: true
      tags: html

    - name: Creating new index.html
      ansible.builtin.blockinfile:
        path: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">

          <head>
              <meta charset="UTF-8" />
              <meta http-equiv="X-UA-Compatible" content="IE=edge" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <link rel="shortcut icon" href="./assets/favicon.ico" type="image/x-icon" />
              <link rel="preconnect" href="https://fonts.googleapis.com" />
              <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
              <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;500&display=swap" rel="stylesheet" />
              <title>Server Stats</title>

              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: inherit;
                  }

                  html {
                      font-size: 62.5%;
                      box-sizing: border-box;
                  }

                  body {
                      font-family: "Oswald", sans-serif;
                      font-weight: 300;
                      height: 100vh;
                      color: #ffffff;
                      background-color: hsl(0, 0%, 11%);
                      display: flex;
                      align-items: center;
                      justify-content: center;
                  }

                  table {
                      height: 300px;
                      border: 5px solid hsl(35, 94%, 87%);
                      margin: 1rem auto 3rem auto;
                      border-radius: 0.2rem;
                  }

                  #serverInfo {
                      width: 100vw;
                      max-width: 768px;
                      font-size: 2em;
                  }

                  .tableHeading {
                      width: 100%;
                      height: 40px;
                      background-color: hsl(35, 94%, 87%);
                      color: #3a3a3a;
                      border-radius: 0.2rem;
                  }

                  .tableRow {
                      height: 70px;
                      padding: 0.35rem;
                  }

                  .serverInfoLabel,
                  .serverInfoValue {
                      padding-left: 2rem;
                      border-radius: 0.2rem;
                  }

                  td.serverInfoLabel {
                      display: flex;
                      align-items: center;
                      width: 100%;
                      height: 70px;
                      color: #3a3a3a;
                      background-color: hsl(34, 100%, 93%);
                      font-weight: 500;
                  }

                  td>svg {
                      width: 32px;
                      height: 32px;
                      margin-right: 10px;
                  }

                  td.serverInfoValue {
                      width: 70%;
                      height: 70px;
                      color: hsl(0, 0%, 100%);
                      background-color: hsla(0, 0%, 23%, 0.39);
                      font-weight: 300;
                  }

                  button {
                      font-family: inherit;
                      cursor: pointer;
                      font-weight: 500;
                      text-transform: uppercase;
                  }

                  button#refreshBtn {
                      color: hsl(0, 0%, 100%);
                      background-color: hsl(204, 84%, 52%);
                      border: none;
                      border-radius: 0.2rem;
                      padding: 1rem 3rem;
                      text-align: center;
                  }

                  .twoColRow {
                      display: flex;
                      flex-direction: row-reverse;
                      align-items: center;
                      justify-content: space-between;
                  }

                  #copyright {
                      font-size: 1.5em;
                  }
              </style>

          </head>

          <body>
              <div id="wrapper">
                  <table id="serverInfo">
                      <tr class="tableRow">
                          <th colspan="2" class="tableHeading">Server Stats</th>
                      </tr>
                      <tr class="tableRow">
                          <td class="serverInfoLabel">
                              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                                  <path
                                      d="M5.507 4.048A3 3 0 017.785 3h8.43a3 3 0 012.278 1.048l1.722 2.008A4.533 4.533 0 0019.5 6h-15c-.243 0-.482.02-.715.056l1.722-2.008z" />
                                  <path fill-rule="evenodd"
                                      d="M1.5 10.5a3 3 0 013-3h15a3 3 0 110 6h-15a3 3 0 01-3-3zm15 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm2.25.75a.75.75 0 100-1.5.75.75 0 000 1.5zM4.5 15a3 3 0 100 6h15a3 3 0 100-6h-15zm11.25 3.75a.75.75 0 100-1.5.75.75 0 000 1.5zM19.5 18a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"
                                      clip-rule="evenodd" />
                              </svg>
                              Hostname
                          </td>
                          <td class="serverInfoValue" id="serverHostname">
                              ip-10-0-1-190.eu-west-2.compute.internal
                          </td>
                      </tr>
                      <tr class="tableRow">
                          <td class="serverInfoLabel">
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                  stroke="currentColor" class="w-6 h-6">
                                  <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M8.288 15.038a5.25 5.25 0 017.424 0M5.106 11.856c3.807-3.808 9.98-3.808 13.788 0M1.924 8.674c5.565-5.565 14.587-5.565 20.152 0M12.53 18.22l-.53.53-.53-.53a.75.75 0 011.06 0z" />
                              </svg>
                              IP Address
                          </td>
                          <td class="serverInfoValue" id="serverIpAddress">
                              35.177.16.137
                          </td>
                      </tr>
                      <tr class="tableRow">
                          <td class="serverInfoLabel">
                              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                                  <path fill-rule="evenodd"
                                      d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zM12.75 6a.75.75 0 00-1.5 0v6c0 .414.336.75.75.75h4.5a.75.75 0 000-1.5h-3.75V6z"
                                      clip-rule="evenodd" />
                              </svg>
                              Timezone
                          </td>
                          <td class="serverInfoValue" id="serverTimezone">
                              Africa/Lagos
                          </td>
                      </tr>
                      <tr class="tableRow">
                          <td class="serverInfoLabel">
                              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                                  <path fill-rule="evenodd"
                                      d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z"
                                      clip-rule="evenodd" />
                              </svg>
                              Server Location
                          </td>
                          <td class="serverInfoValue" id="serverLocation">
                              London (eu-west-2a)
                          </td>
                      </tr>
                  </table>
                  <div class="twoColRow">
                      <button id="refreshBtn" onclick="location.reload();">Refresh</button>
                      <p id="copyright">Finessed by 😎: Patrick Aziken</p>
                  </div>
              </div>
          </body>

          </html>
        marker: ""
        owner: www-data
        group: www-data
        mode: '0775'
      changed_when: true
      tags: html
